# Site settings
baseurl = "https://ramgo.li/"
themesDir = "./themes"
languageCode = "en-us"
title = "Blog | Ram Goli"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-125743916-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = "ramsg"

[params]
	name = "Ram Goli"
	description = "student, programmer, frisbee player, aspiring entrepreneur and blogger"
	bio = "student, programmer, frisbee player, aspiring entrepreneur and blogger"
	# Enter optionally your twitter account
	twitter = "ramsgoli"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = ["css/custom-style.css"]
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Just a guy being a guy"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/"
    facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/ramsgoli/"
